package com.mobi.iou.server;

import org.restlet.Application;
import org.restlet.Restlet;
import org.restlet.routing.Router;
import org.restlet.routing.Template;

import com.mobi.iou.server.login.LoginResource;


public class IOUApplication extends Application {

	@Override
    public Restlet createInboundRoot() {
		Router router = new Router(getContext());
        //getConnectorService().getClientProtocols().add(Protocol.FILE);

        // Serve the files generated by the GWT compilation step.
        /*File warDir = new File("");
        if (!"war".equals(warDir.getName())) {
            warDir = new File(warDir, "war/");
        }*/

        //Directory dir = new Directory(getContext(), LocalReference.createFileReference(warDir));
        //router.attachDefault(dir);

		router.setDefaultMatchingMode(Template.MODE_STARTS_WITH);
		
		router.attach("/iou/login", LoginResource.class);
		router.attach("/iou/summary", AccountSummaryResource.class);
		router.attach("/iou/accountlineitem", AccountLineItemResource.class);

 
        return router;
    }
}
